project_id = "wixzqilqithhlybhyite"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"

[db]
enabled = true
port = 54322

[functions]
enabled = true
verify_jwt = false

[functions.ai-host-chat]
verify_jwt = false

[functions.ai-host-voice]
verify_jwt = false